#!/usr/bin/env python3
"""Record actual offline build/runtime identities; never resolve 'latest'.

The report supplements (does not redefine) the engine fingerprint. Package file
hashes cover the installed optional SDK dependency closure, not all system Python.
No environment variable values, credentials, account files or network calls.
"""
from __future__ import annotations
import argparse
import datetime
import hashlib
import importlib.metadata as metadata
import json
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path
from compression_lab import inventory, runner


def digest(path):
    h=hashlib.sha256()
    with Path(path).open('rb') as f:
        for block in iter(lambda:f.read(1024*1024),b''):h.update(block)
    return h.hexdigest()


def file_record(path):
    p=Path(path)
    return {'path':str(p),'resolved_path':str(p.resolve()),'bytes':p.stat().st_size,'sha256':digest(p)}


def python_closure():
    pending=['mcp','setuptools'];seen=set();rows=[]
    while pending:
        name=pending.pop(0).lower().replace('_','-')
        if name in seen:continue
        seen.add(name)
        try:d=metadata.distribution(name)
        except metadata.PackageNotFoundError:
            rows.append({'name':name,'installed':False});continue
        requirements=d.requires or [];files=[]
        for item in d.files or []:
            # RECORD and generated bytecode are installation-dependent. Record
            # existing distribution-owned regular bytes, excluding editable .pth
            # targets outside the declared distribution rather than walking them.
            p=Path(d.locate_file(item))
            if p.is_file() and p.suffix not in ('.pyc','.pyo'):
                files.append({'path':str(item),'bytes':p.stat().st_size,'sha256':digest(p)})
        for requirement in requirements:
            # Report a conservative installed closure; optional requirements are
            # followed if installed, with missing options shown, not installed.
            match=re.match(r'\s*([A-Za-z0-9_.-]+)',requirement)
            if match:pending.append(match.group(1))
        rows.append({'name':d.metadata.get('Name',name),'version':d.version,'installed':True,
            'license_expression':d.metadata.get('License-Expression'),
            'license_metadata':d.metadata.get('License'),
            'license_classifiers':[v for v in d.metadata.get_all('Classifier',[]) if v.startswith('License ::')],
            'project_urls':d.metadata.get_all('Project-URL',[]),'requires_dist':requirements,
            'files':files,'hash_scope':'Actual installed regular files from distribution RECORD, excluding pyc/pyo; no proof of pristine upstream installation.'})
    return sorted(rows,key=lambda r:r['name'].lower())


def observe():
    tools={}
    for name in ('gcc','g++','ld','ar','strip','readelf','unshare','bwrap'):
        path=shutil.which(name)
        if not path:tools[name]={'available':False};continue
        result=subprocess.run([path,'--version'],capture_output=True,text=True,timeout=10)
        tools[name]={'available':True,**file_record(path),'version_output':(result.stdout+result.stderr)[:4000]}
    headers=[]
    for pattern in ('zstd*.h','lz4*.h','lzma.h','lzma/*.h','brotli/*.h','xxhash.h'):
        for path in sorted(Path('/usr/include').glob(pattern)):
            if path.is_file():headers.append(file_record(path))
    return {'schema_version':1,'observed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),
        'network_requests':False,'claims_latest_installed':False,'platform':platform.platform(),
        'uid':os.geteuid(),'python':{'version':sys.version,'executable':sys.executable,
            'executable_sha256':digest(sys.executable),'prefix':sys.prefix,'base_prefix':sys.base_prefix},
        'runtime_fingerprint':runner.fingerprint(),'native':inventory.inspect(),'native_headers':headers,
        'tools':tools,'python_distributions':python_closure(),
        'scope':'Observed identities, not a package installer or full reproducible OS image. Current upstream releases are in dependencies/upstream-lock.json. OS/compiler transitive inputs beyond the listed files are not asserted fully hermetic.'}


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output',required=True,type=Path);a=p.parse_args()
    if a.output.exists():p.error('Choose a new output; an observation is never overwritten')
    report=observe();a.output.parent.mkdir(parents=True,exist_ok=True)
    with a.output.open('x') as f:json.dump(report,f,indent=2);f.write('\n')
    print(json.dumps({'status':'recorded','output':str(a.output),'sha256':digest(a.output),'latest_claim':False}))

if __name__=='__main__':main()
